version: '2'
services:
    vlsm:
        build: .
        container_name: vlsm
        restart: always
        ports:
        - "8008:80"
        tty: true
#        networks:
#         - hotsite_marco-net

#networks:
#    hotsite_marco-net:
#        external: true
